### ISSUE TITLE
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

### ISSUE THREAD

**Issue by teror4uks** [lundberg/respx#163] opened 2021-09-10 08:59 UTC
Hello.

For some reason `httpx==0.19.0` is not working with `respx==0.17.1` properly if `httpx.AsyncClient` using hooks behavior. If run the current test it will fail with the exception

```
client_app = <starlette.testclient.TestClient object at 0x7f4f71eb1640>

    def test_app_for_test(client_app: TestClient) -> None:
        with respx.mock(
            base_url='https://test.com',
            assert_all_called=True,
            assert_all_mocked=True,
        ) as respx_mock:
            respx_mock.post('/post').respond(status_code=400, text='Bad request')
>           response = client_app.post('/endpoint', json={'body': 'data'})

tests/test.py:27: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../respx_bug/venv/lib/python3.8/site-packages/requests/sessions.py:590: in post
    return self.request('POST', url, data=data, json=json, **kwargs)
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/testclient.py:415: in request
    return super().request(
../../../respx_bug/venv/lib/python3.8/site-packages/requests/sessions.py:542: in request
    resp = self.send(prep, **send_kwargs)
../../../respx_bug/venv/lib/python3.8/site-packages/requests/sessions.py:655: in send
    r = adapter.send(request, **kwargs)
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/testclient.py:243: in send
    raise exc from None
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/testclient.py:240: in send
    loop.run_until_complete(self.app(scope, receive, send))
/home/t4ks/.pyenv/versions/3.8.8/lib/python3.8/asyncio/base_events.py:616: in run_until_complete
    return future.result()
../../../respx_bug/venv/lib/python3.8/site-packages/fastapi/applications.py:208: in __call__
    await super().__call__(scope, receive, send)
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/applications.py:112: in __call__
    await self.middleware_stack(scope, receive, send)
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/middleware/errors.py:181: in __call__
    raise exc from None
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/middleware/errors.py:159: in __call__
    await self.app(scope, receive, _send)
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/exceptions.py:82: in __call__
    raise exc from None
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/exceptions.py:71: in __call__
    await self.app(scope, receive, sender)
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/routing.py:580: in __call__
    await route.handle(scope, receive, send)
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/routing.py:241: in handle
    await self.app(scope, receive, send)
../../../respx_bug/venv/lib/python3.8/site-packages/starlette/routing.py:52: in app
    response = await func(request)
../../../respx_bug/venv/lib/python3.8/site-packages/fastapi/routing.py:226: in app
    raw_response = await run_endpoint_function(
../../../respx_bug/venv/lib/python3.8/site-packages/fastapi/routing.py:159: in run_endpoint_function
    return await dependant.call(**values)
main.py:21: in endpoint
    return responses.JSONResponse(status_code=400, content={'status': 'error', 'detail': e.response.text})
../../../respx_bug/venv/lib/python3.8/site-packages/httpx/_models.py:1314: in text
    content = self.content

self = <Response [400 Bad Request]>

    @property
    def content(self) -> bytes:
        if not hasattr(self, "_content"):
>           raise ResponseNotRead()
E           httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.

```

PR with the bug reproducing - https://github.com/lundberg/respx/pull/162

**Comment by lundberg** [comment] 2021-09-10 13:56
Thanks for reporting @teror4uks!

It's probably due to "cloning" of HTTPX iterable streams when mocking, will take a look and see what we can do about it.

**Comment by lundberg** [comment] 2021-09-10 15:01
After testing and thinking this over, it looks like this is the cause and behaviour of HTTPX, and has nothing to do with RESPX mocking this response.

The `httpx.ResponseNotRead` exception is caused by reading the `e.response.text` in your endpoint during the http status error handling.

Looking at the HTTPX client code, the event hooks are fired [here](https://github.com/encode/httpx/blob/0b4a83257bef85559d91b466e4ac94a216a25485/httpx/_client.py#L1657-L1669), before the response stream is read [here](https://github.com/encode/httpx/blob/0b4a83257bef85559d91b466e4ac94a216a25485/httpx/_client.py#L1595). In other words, if a HTTPX response hook raises an exception, the response content will not be read automatically by the client.

You'll need to add `await e.response.aread()` before building your endpoint error response.

Might we worth a HTTPX issue or discussion to see if it would be of interest handling exceptions raised by a hook in the client someway?

**Comment by lundberg** [comment] 2021-09-10 15:27
Hmm, tried my suggestion of adding `await e.response.aread()`, and it turned out that that raises another HTTPX error:

`httpx.StreamClosed: Attempted to read or stream content, but the stream has been closed.`

Looking again at the HTTPX client code...the response is closed by the client if any exception is raised [here](https://github.com/encode/httpx/blob/0b4a83257bef85559d91b466e4ac94a216a25485/httpx/_client.py#L1675), e.g. by an event hook.

Could you help verify that this is a HTTPX related problem, i.e. test without RESPX involved/mocked?

**Comment by teror4uks** [comment] 2021-09-11 07:37
hey, sure I will try to check the problem without RESPX.

By the way, Response class in the `httpx` has in the init the code where is `read()` fired when you instantiate a new instance [here](https://github.com/encode/httpx/blob/0b4a83257bef85559d91b466e4ac94a216a25485/httpx/_models.py#L1222-L1228) . I thought it should work when you mocking response, but seems I missed some important things :thinking:

**Comment by lundberg** [comment] 2021-09-12 08:40
> By the way, Response class in the `httpx` has in the init the code where is `read()` fired when you instantiate a new instance [here](https://github.com/encode/httpx/blob/0b4a83257bef85559d91b466e4ac94a216a25485/httpx/_models.py#L1222-L1228) . I thought it should work when you mocking response, but seems I missed some important things 🤔

True, the response/stream will be read on `Response` instantiation, but only when instantiated directly with content (text or json etc), not with a stream. This is not the case when responses are instantiated by the HTTPX client when making the requests, where it's always instantiated with the content stream from underlaying sync, or async, transport.

To not have any false positives, RESPX is mocking the transports, meaning the mocked `Response` you supply is not the same instance that you will receive from the HTTPX client, i.e. it will have been re-instantiated with a stream by the client containing the content of the mocked response instance.

**Comment by teror4uks** [comment] 2021-09-13 13:48
> Could you help verify that this is a HTTPX related problem, i.e. test without RESPX involved/mocked?

I've tried the real endpoint with hooks and you are right it's HTTPX related problem, I'll create an issue with found bug there. Thanks for the help with the investigation :) 

> meaning the mocked Response you supply is not the same instance that you will receive from the HTTPX client

Ah, thanks for the explanation.

**Comment by teror4uks** [comment] 2021-09-13 14:19
created discussion -> https://github.com/encode/httpx/discussions/1856

**Comment by teror4uks** [comment] 2021-09-13 15:58
so the issue was solved by adding an additional check before calling raise_for_status() method

```python
if response.is_error:
    await response.aread()
    response.raise_for_status()
```

**Comment by lundberg** [comment] 2021-09-14 06:11
Great, closing this issue and the related PR then. Thanks anyways for the discussion, always interesting see usages and tackle obstacles.

**Closed by lundberg** 2021-09-14 06:11 UTC
